version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "gin"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "kubernetes"
    schedule:
      interval: "daily"
